### ISSUE TITLE
XMLSchema instance should not be imported

### ISSUE THREAD

**Issue by BastiaanGrutters** [buildingSMART/IDS#55] opened 2022-03-18 09:29 UTC
https://github.com/buildingSMART/IDS/blob/80af13fed221256b8bf7073d33637c60b3aab5cf/Development/0.5/ids_05.xsd#L6

As far as I understand it it should just be used for namespace declaration but should not be imported.
See: https://www.w3.org/2001/XMLSchema-instance

Removing the import line allows validating for example: https://github.com/buildingSMART/IDS/blob/master/Development/0.5/IDS_ucms_prefab_pipes_IFC4.3.xml
With the import it fails on parsing schema.

**Comment by rubendel** [comment] 2022-04-05 10:17
Duplicate of https://github.com/buildingSMART/IDS/issues/24

**Closed** 2022-08-08 07:41 UTC
