### ISSUE TITLE
hints about ids version 0.5.10

### ISSUE THREAD

**Issue by aristotls** [buildingSMART/IDS#53] opened 2022-02-22 18:33 UTC
Some hints about ids schema 0.5.10, possibly to be checked:
* instructions (all "instructions" attributes)
  * datatype not defined (used to be string in earlier versions)
  * cardinality == 1 --> must it be mandatory?
* specification.identifier
  * datatype not defined

**Comment by berlotti** [comment] 2022-02-22 18:37
ifc or ids?
could you be a bit more specific?

**Comment by aristotls** [comment] 2022-02-22 18:43
ids! sorry for confusion

**Comment by CBenghi** [comment] 2022-02-22 23:26
Hi @aristotls,
Are you are referring to the attribute of facets? To be clear I mean something like:

https://github.com/buildingSMART/IDS/blob/425e89352c3140452aec9190f6c5d1497ac85c7e/Development/0.5/ids_05.xsd#L241

If that's the case attributes use is optional (not required) by default and the type is `xsd:anySimpleType`; see https://stackoverflow.com/questions/29845983/xml-schema-whats-the-default-type-of-an-xsdattribute.

Same goes for `specification.identifier`.

**Comment by aristotls** [comment] 2022-02-23 07:54
yes, I am referring to these elements. 
I would prefer having an explicit declaration, as we have it for all other attributes. To have a uniform specification.

**Comment by CBenghi** [comment] 2022-02-23 08:15
Yes, restricting the type of `instructions` to `string` might also be a good idea.

**Comment by berlotti** [comment] 2022-02-25 09:41
Yes; this was intended to be string. Will make it explicit in XSD.

**Comment by berlotti** [comment] 2022-03-01 11:16
fixed in 0.5.11

**Closed by berlotti** 2022-03-01 11:16 UTC
