### ISSUE TITLE
Add instructions to ReguirementsType.Entity

### ISSUE THREAD

**Issue by pasi-paasiala** [buildingSMART/IDS#167] opened 2023-06-15 05:58 UTC
Other ReguirementsType classes have instructions, but [Entity](https://github.com/buildingSMART/IDS/blob/master/Development/ids.xsd#L113) doesn't.

**Comment by CBenghi** [comment] 2023-06-16 06:37
Hi @pasi-paasiala, 
closing, because it's a duplicate of #122

**Closed by CBenghi** 2023-06-16 06:37 UTC
