### ISSUE TITLE
Wrong file name in the entity directory of test cases

### ISSUE THREAD

**Issue by enzoaggazioALMA** [buildingSMART/IDS#313] opened 2024-06-06 08:11 UTC
The file pass-userdefuned_predefined_types_may_be_specified.ids file name in entity test cases directory is wrong. 
Should be renamed in  pass-userdefined_predefined_types_may_be_specified.ids.

**Comment by rubendel** [comment] 2024-06-06 14:27
Duplicate of https://github.com/buildingSMART/IDS/issues/308

**Closed as completed** 2024-06-12 15:45 UTC
